### ISSUE TITLE
create forestry plugin

### ISSUE THREAD

**Issue by iosefa** [hyakumori/docker-gtt#2]
Create a "Forestry" plugin with customization specifically tailored for the needs of Hyakumori. This should be a dedicated plugin and only contain features/changes that are necessary and configurable through the existing "core" plugins (ref #1 ).

**Comment by iosefa** [comment]
this is probably not necessary, but instead of this some sort of automation task (rake) to provide initial default values that can be applied for hyakumori will be good.

**Comment by sanak** [comment]
@dkastl, @iosefa
As we discussed at yesterday, this functionality is now provided at https://github.com/gtt-project/redmine_gtt_smash.
I will close this.
