### ISSUE TITLE
Implement Hyakumori Theme

### ISSUE THREAD

**Issue by iosefa** [hyakumori/docker-gtt#3]
Implement a simple theme for hyakumori that features hyakumori colors and related designs.

**Comment by sanak** [comment]
@iosefa, @dkastl  
I think that this is already done.

**Comment by iosefa** [comment]
yes. Thanks. I will close this issue and if we notice tweaks to be made we can open new issues. Thanks!

**Comment by iosefa** [comment]
(note, this is applied on the `hyakumori` branch)
